### ISSUE TITLE
Error on serialization

### ISSUE THREAD

**Issue by cbertelli** [evuez/ditherer#1]
I tried to build with cargo (version 1.37.0) and I got an error on serde:
````
error[E0642]: patterns aren't allowed in methods without bodies
````
Is there a way to fix this?

**Comment by evuez** [comment]
I pushed a commit on master that should fix this :slightly_smiling_face: 

Just updated the dependencies and used `image::GenericImageView` instead of `image::GenericImage`.

**Comment by cbertelli** [comment]
Thanks. Now it builds without glitches and it runs well albeit very slowly.
When I run it without arguments it throws an unpleasant error instead of showing usage, as usual
````
$ ./ditherer
thread 'main' panicked at 'Wrong number of arguments!', src/main.rs:11:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
````
nor it replies kindly when help is requested
````
$ ./ditherer --help
````
anyway the result is really good.

**Comment by evuez** [comment]
It definitely lacks optimizations and good user experience, sorry about that.

If you submit a PR to improve that I'll happily merge it though :slightly_smiling_face:
